# The Site Configuration

# 引入主题
theme: jekyll-theme-chirpy

# 网页语言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果网页语言与 `_data/locales` 文件夹中的文件名相同，布局语言也将被更改。
# 否则，布局语言将使用默认值 'en'。
# 多语言支持  中文 zh-CN
lang: zh-CN

# 修改时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

# 主标题
title: DeathWhispers

# 副标题
tagline: 个人学习 | 日常记录 | 存档

# 网站描述，用于 seo meta 和 atom  feed
description: >- 
  A minimal, responsive and feature-rich Jekyll theme for technical writing.
  feedId:215973636224961536+userId:215706615374815232

# 填写网站协议和主机名
# E.g. 'https://username.github.io', 网站 URL，注意结尾没有 '/'
url: "https://deathwhispers.github.io"

github:
  username: deathwhispers # 修改成你的 GitHub 用户名

twitter:
  username: twitter_username # 修改成你的 Twitter 用户名

social:
  # 填写你的全名
  # 它将显示为文章的默认作者和页脚的版权所有者
  name: deathwhispers
  # 修改成你的邮箱地址
  email: guangjian.yang@qq.com
  links:
    # 第一个元素作为版权所有者的链接
    - https://twitter.com/username # 修改成你的 Twitter 主页
    - https://github.com/deathwhispers # 修改成你的 GitHub 主页
    # 取消注释以下行添加更多社交链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 填写你的网站验证代码
webmaster_verifications:
  google: NGRVqWbZ5HjBaO2fo8VwxvyhWTL1lHmYu-uia58MVMw
  bing: # 修改成你的 Bing 验证代码
  alexa: # 修改成你的 Alexa 验证代码
  yandex: # 修改成你的 Yandex 验证代码
  baidu: # 修改成你的 Baidu 验证代码
  facebook: # 修改成你的 Facebook 验证代码

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# 填写你的分析工具 ID
analytics:
  google:
    id: G-3KHTSZFS3Z
  goatcounter:
    id: # 修改成你的 GoatCounter ID
  umami:
    id: # 修改成你的 Umami ID
    domain: # 修改成你的 Umami domain
  matomo:
    id: # 修改成你的 Matomo ID
    domain: # 修改成你的 Matomo domain
  cloudflare:
    id: # 修改成你的 Cloudflare Web Analytics token
  fathom:
    id: # 修改成你的 Fathom Site ID

# 填写你的页面视图统计工具 ID
pageviews:
  provider: # 当前仅支持 'goatcounter'

# 填写你偏好的颜色方案
#
# Note: 保持为空将遵循系统偏好的颜色方案，
# 并在侧边栏的左下角提供切换主题的选项（亮色和暗色）。
#
# 可选值：
#
#     light — 使用亮色方案
#     dark — 使用暗色方案
#
theme_mode:

# The CDN endpoint for media resources.
# 注意：一旦赋值，CDN URL 将被添加到所有以 '/' 开头的媒体资源路径中（站点头像、文章图片、音频和视频文件）
#
# e.g. 'https://cdn.com'
cdn:

# 侧边栏头像，支持本地或 CORS 资源
avatar: /assets/img/avatar.png

# 站点全局社交预览图片，用于 SEO `og:image` meta 标签。
# 可以在文章 Front Matter 中自定义 `page.image` 覆盖此设置。
social_preview_image: # 字符串，本地或 CORS 资源

# 布尔类型，全局开关文章中的目录（TOC）。
toc: true

comments:
  # 配置评论系统，如果为空则禁用评论功能 [disqus | utterances | giscus]
  provider: giscus
  # Disqus 评论系统配置
  disqus:
    # 评论系统短名，前往 Disqus 注册获取 › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    # Disqus
    shortname:
  # Giscus 评论系统配置 › https://utteranc.es/
  utterances:
    # Utterances 评论系统仓库，格式为 <gh-username>/<repo>
    repo: deathwhispers/deathwhispers.github.io
    # Utterances 评论系统问题分类，可选值为 'url', 'pathname', 'title', 'og:title'，默认值为 'pathname'
    issue_term:
  # Giscus 评论系统配置 › https://giscus.app
  giscus:
    # Giscus 评论系统仓库，格式为 <gh-username>/<repo>
    repo: deathwhispers/deathwhispers.github.io
    # Giscus 评论系统仓库 ID，前往 Giscus 注册获取 › https://giscus.app
    repo_id: R_kgDOHCEyLA
    # Giscus 评论系统分类，前往 Giscus 注册获取 › https://giscus.app
    category: General
    # Giscus 评论系统分类 ID，前往 Giscus 注册获取 › https://giscus.app
    category_id: DIC_kwDOHCEyLM4Cv5_n
    # Giscus 评论系统映射，可选值为 'url', 'pathname', 'title', 'og:title'，默认值为 'pathname'
    mapping: pathname
    # Giscus 评论系统严格模式，可选值为 '0' 或 '1'，默认值为 '0'
    strict: 0
    # Giscus 评论系统输入位置，可选值为 'top' 或 'bottom'，默认值为 'bottom'
    input_position: top
    # Giscus 评论系统语言，默认值为 `site.lang`
    lang:
    # Giscus 评论系统是否启用反应，可选值为 '0' 或 '1'，默认值为 '1'
    reactions_enabled:
    # Giscus 评论系统讨论分类，默认值为 '导航点击统计'
    discussion_category: '导航点击统计'

# 自托管静态资源配置 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    # 是否启用自托管静态资源，空值表示 false
    enabled:
    # 指定 Jekyll 环境，空值表示同时适用于开发和生产环境
    # 仅在 `assets.self_host.enabled` 为 'true' 时生效
    env: # [development | production]

pwa:
  # 是否启用 PWA 功能（可安装），默认值为 true
  enabled: true
  cache:
    # 是否启用 PWA 离线缓存，默认值为 true
    enabled: true
    # 定义要排除在 PWA 缓存之外的路径。
    # 通常其值为另一个共享相同域名的网站的 `baseurl`。
    deny_paths:
    # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

# 分页设置，默认值为 10
paginate: 10

# 站点基础 URL，默认值为空
baseurl: ""

# ------------ 以下配置均不推荐修改 ------------------
# Kramdown 配置
kramdown:
  # 脚注返回链接
  footnote_backlink: "&#8617;&#xfe0e;"
  # 语法高亮器，默认值为 rouge
  syntax_highlighter: rouge
  # Rouge 语法高亮器选项 › https://github.com/jneen/rouge#full-options
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order
  articles:
    output: true

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post       # 所有文件默认使用 post 布局
      toc: true          # 默认开启 TOC
      comments: true     # 默认开启评论
      math: true
      mermaid: true
      render_with_liquid: false
      permalink: /posts/:year/:month/:day/:slug/
  - scope:
      path: _drafts
    values:
      comments: false # 覆盖上面的 comments: true
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page # 覆盖上面的 layout: post
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [ development ]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - .obsidian

jekyll-archives:
  enabled: [ categories, tags ]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
