# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
# 多语言支持  中文 zh-CN
lang: zh-CN

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

# the main title
title: DeathWhispers

# it will display as the subtitle
tagline: 个人学习 | 日常记录 | 存档

description: >- # used by seo meta and the atom feed
  A minimal, responsive and feature-rich Jekyll theme for technical writing.
  feedId:215973636224961536+userId:215706615374815232

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://deathwhispers.github.io"

github:
  username: deathwhispers # change to your GitHub username

twitter:
  username: twitter_username # change to your Twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: deathwhispers
  email: guangjian.yang@qq.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/username # change to your Twitter homepage
    - https://github.com/deathwhispers # change to your GitHub homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Site Verification Settings
webmaster_verifications:
  google: NGRVqWbZ5HjBaO2fo8VwxvyhWTL1lHmYu-uia58MVMw
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: G-3KHTSZFS3Z
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light — Use the light color scheme
#     dark — Use the dark color scheme
#
theme_mode:

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn:

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/avatar.png

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # 配置评论系统，如果为空则禁用评论功能 [disqus | utterances | giscus]
  provider: giscus
  # Disqus 评论系统配置
  disqus:
    # Disqus 评论系统短名，前往 Disqus 注册获取 › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    shortname:
  # Giscus 评论系统配置 › https://utteranc.es/
  utterances:
    # Utterances 评论系统仓库，格式为 <gh-username>/<repo>
    repo: deathwhispers/deathwhispers.github.io
    # Utterances 评论系统问题分类，可选值为 'url', 'pathname', 'title', 'og:title'，默认值为 'pathname'
    issue_term:
  # Giscus 评论系统配置 › https://giscus.app
  giscus:
    # Giscus 评论系统仓库，格式为 <gh-username>/<repo>
    repo: deathwhispers/deathwhispers.github.io
    # Giscus 评论系统仓库 ID，前往 Giscus 注册获取 › https://giscus.app
    repo_id: R_kgDOHCEyLA
    # Giscus 评论系统分类，前往 Giscus 注册获取 › https://giscus.app
    category: General
    # Giscus 评论系统分类 ID，前往 Giscus 注册获取 › https://giscus.app
    category_id: DIC_kwDOHCEyLM4Cv5_n
    # Giscus 评论系统映射，可选值为 'url', 'pathname', 'title', 'og:title'，默认值为 'pathname'
    mapping: pathname
    # Giscus 评论系统严格模式，可选值为 '0' 或 '1'，默认值为 '0'
    strict: 0
    # Giscus 评论系统输入位置，可选值为 'top' 或 'bottom'，默认值为 'bottom'
    input_position: top
    # Giscus 评论系统语言，默认值为 `site.lang`
    lang:
    # Giscus 评论系统是否启用反应，可选值为 '0' 或 '1'，默认值为 '1'
    reactions_enabled:
    # Giscus 评论系统讨论分类，默认值为 '导航点击统计'
    discussion_category: '导航点击统计'

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    # 是否启用自托管静态资源，空值表示 false
    enabled:
    # 指定 Jekyll 环境，空值表示同时适用于开发和生产环境
    # 仅在 `assets.self_host.enabled` 为 'true' 时生效
    env: # [development | production]

pwa:
  # 是否启用 PWA 功能（可安装），默认值为 true
  enabled: true
  cache:
    # 是否启用 PWA 离线缓存，默认值为 true
    enabled: true
    # 定义要排除在 PWA 缓存之外的路径。
    # 通常其值为另一个共享相同域名的网站的 `baseurl`。
    deny_paths:
    # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

# 分页设置，默认值为 10
paginate: 10

# 站点基础 URL，默认值为空
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------
# Kramdown 配置
kramdown:
  # 脚注返回链接
  footnote_backlink: "&#8617;&#xfe0e;"
  # 语法高亮器，默认值为 rouge
  syntax_highlighter: rouge
  # Rouge 语法高亮器选项 › https://github.com/jneen/rouge#full-options
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order
  articles:
    output: true

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post       # 所有文件默认使用 post 布局
      toc: true          # 默认开启 TOC
      comments: true     # 默认开启评论
      math: true
      mermaid: true
      render_with_liquid: false
      permalink: /posts/:year/:month/:day/:slug/
  - scope:
      path: _drafts
    values:
      comments: false # 覆盖上面的 comments: true
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page # 覆盖上面的 layout: post
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [ development ]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - .obsidian

jekyll-archives:
  enabled: [ categories, tags ]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
